### PR TITLE
Live toggling

### PR DESCRIPTION
**Pull request by holantomas**
Enable live collapsing when inner entities change state.

It was all the time in HA small doc page about custom card (facepalm).

Still testing if there is no error cause by time, but this looks promissing, what do you think?

### CODE REVIEW

**Comment by holantomas** [comment]
Should I resolv conflict or you don't want this? I have prepared another PR for changing from custom component to native HA expandable panel which reduce need for logic in source and use native HA design. But now it need a lot of work

**Comment by RossMcMillan92** [comment]
To be honest, I'm not sure what this does, and it seems like a big change to merge in without caution as I have been otherwise. I think we need to start testing the component before making changes so big.

**Comment by holantomas** [comment]
And. I spend more time to getting know how things in HA works then I wanted/like to. So it will be sad if this will disappear 😐 second I spend a lot of time of revers engineering to get native ha-expand-panel working in custom card to reduce logic and style. I was only waiting for this merge, now is my work stack of nothing because I need to rewrite it all. I was also preparing to create PR for adding this to default HACS repository. So users don't have to do it manually.

**Comment by holantomas** [comment]
And one more thing. This PR adds more security of whole component. Actual code doesn't count with another stack card inside, like vertical, horizontal, grid or just another this custom card. It doesn't count that all cards doesn't have entity property but have entities or don't have any of these (will cause all times open state for markdown card as example) property, or for example thermostat card don't have config property but have ___config. My code solve all of this, doing recursive traversing thru stacks and try to check everything. Didn't have time to check all kind of cards but what i guess most used are covered. This is result of hours and hours revers engineering, try and failing. So, please talk to me what you need to know to get it merge because it will be harder and harder to sync it with main branch.

**Comment by RossMcMillan92** [comment]
Ok, that sounds good. Thanks for explaining. Looks like there's a conflict in the branch, but once that's fixed I'll merge it in.

**Pull request closed without merging**
