### PR TITLE
Live toggling

### PR DESCRIPTION
**Pull request by holantomas**
Github just closed old PR, because I had to sync my fork for testing. There is synced source from last PR - nothing was added.

### CODE REVIEW

**Comment by holantomas** [comment]
BTW now I see why did you complain ... Github diff did just one big mess. There are not so big changes. I just add/changed few lines and add some new functions, renamed class name cause you did take one from VerticalStackCard and I don't know if there can be some conflicts(and it looks better). As last thing I removed first line which was there for nothing, it just print in browser console wrong component version. If you want to see, open in some better diff.

**Comment by holantomas** [comment]
@andrzejl yeah, my IDE doing this by default settings(both - hodině whitespace changes and auto-fix them) 😁. I'm used to use all kind of QA, lints, etc. This developing by scratch is new for me 😁

**Comment by RossMcMillan92** [comment]
Thank you my friend, let's get it in

**Comment by holantomas** [comment]
@RossMcMillan92 thanks, I'm going to sync my last modifications.

**Pull request merged**
